// ===================================================================
//  Diridari Erfassung – Sprachfile
//  Etappe C1
//
//  Aufbau: pro Sprache ein Objekt mit Schluessel/Text-Paaren. Neue
//  Texte immer in ALLEN drei Sprachen ergaenzen. Platzhalter in
//  geschweiften Klammern, z. B. {anzahl}, werden von t() ersetzt.
// ===================================================================

const LANG = {
  de: {
    app_titel:            "BudgetView",
    untertitel:           "Belege unterwegs erfassen",
    nav_erfassen:         "Erfassen",
    nav_inbox:            "Inbox",
    nav_einstellungen:    "Einstellungen",

    // Erfassen-Ansicht
    erfassen_titel:       "Erfassen",
    typ_ausgabe:          "Ausgabe",
    typ_einnahme:         "Einnahme",
    feld_datum:           "Datum",
    feld_betrag:          "Betrag",
    feld_konto:           "Konto",
    feld_hauptkat:        "Hauptkategorie",
    feld_unterkat:        "Unterkategorie",
    feld_beschreibung:    "Beschreibung",
    ph_bitte_waehlen:     "Bitte wählen",
    ph_beschreibung:      "z. B. Wocheneinkauf",
    btn_speichern:        "Buchung speichern",
    feld_belege:          "Belege",
    foto_hinzufuegen:     "Foto hinzufügen",
    foto_entfernen:       "Foto entfernen",
    fehler_foto:          "Das Foto konnte nicht verarbeitet werden.",
    fehler_speichern:     "Die Buchung konnte nicht gespeichert werden.",
    erfolg_gespeichert:   "Buchung gespeichert.",
    fehler_pflicht:       "Bitte Betrag, Konto und Kategorie ausfüllen.",
    fehler_betrag:        "Bitte einen gültigen Betrag eingeben.",

    // Hinweis: keine Stammdaten
    keine_sd_titel:       "Noch keine Stammdaten",
    keine_sd_text:        "Bitte laden Sie zuerst unter „Einstellungen“ Ihre Konten und Kategorien vom PC.",
    keine_sd_btn:         "Zu den Einstellungen",

    // Inbox-Ansicht
    inbox_titel:          "Inbox",
    inbox_leer:           "Noch keine Buchungen erfasst.",
    inbox_anzahl:         "{anzahl} Buchung(en) warten auf den Export",
    inbox_loeschen:       "Löschen",
    inbox_bearbeiten:     "Bearbeiten",
    inbox_export:         "Buchungen exportieren",
    export_titel:         "Export verschlüsseln",
    export_text:          "Vergeben Sie ein Passwort. Sie brauchen es beim Import am PC wieder. Ohne das Passwort sind die Daten nicht lesbar.",
    export_pw1:           "Passwort",
    export_pw2:           "Passwort wiederholen",
    export_btn:           "Exportieren",
    btn_speichern_datei:  "Speichern",
    btn_teilen:           "Teilen",
    btn_weiter:           "Weiter",
    btn_schliessen:       "Schließen",
    phase2_titel:         "Export bereit",
    phase2_text:          "Ihre Datei ist verschlüsselt. Wie möchten Sie sie weitergeben?",
    fehler_pw_leer:       "Bitte ein Passwort eingeben.",
    fehler_pw_ungleich:   "Die Passwörter stimmen nicht überein.",
    fehler_export_leer:   "Es sind keine Buchungen zum Exportieren vorhanden.",
    fehler_export:        "Der Export ist fehlgeschlagen.",
    erfolg_export:        "Buchungen wurden verschlüsselt exportiert.",
    loeschen_titel:       "Übertragung erfolgreich",
    loeschen_frage:       "Die {anzahl} übertragenen Buchungen jetzt vom Handy löschen?",
    loeschen_datei_hinweis: "Die Datei „{datei}“ liegt jetzt im Download-Ordner. Nach dem Import am PC können Sie sie dort gefahrlos löschen.",
    loeschen_ja:          "Ja, löschen",
    loeschen_nein:        "Nein, behalten",
    loeschen_erfolg:      "Übertragene Buchungen gelöscht.",
    pw_titel_festlegen:   "Passwort festlegen",
    pw_titel_eingeben:    "Passwort eingeben",
    pw_text_festlegen:    "Legen Sie ein Passwort für den Export fest. Sie brauchen es beim Import am PC. Der optionale Hinweis hilft Ihnen, falls Sie es vergessen.",
    pw_text_eingeben:     "Geben Sie Ihr Export-Passwort ein.",
    pw_hinweis_ph:        "Passwort-Hinweis (optional)",
    pw_hinweis_label:     "Ihr Hinweis: {hinweis}",
    fehler_pw_falsch:     "Falsches Passwort.",
    fehler_teilen_nicht:  "Teilen wird auf diesem Gerät nicht unterstützt. Bitte „Speichern“ verwenden.",
    fehler_teilen_fehler: "Teilen fehlgeschlagen (Grund: {grund}).",
    erfassen_titel_bearbeiten: "Buchung bearbeiten",
    btn_aenderungen:      "Änderungen speichern",
    btn_abbrechen:        "Abbrechen",

    // Einstellungen-Ansicht
    einstellungen_titel:  "Einstellungen",
    sprache_titel:        "Sprache",
    stammdaten_titel:     "Stammdaten vom PC",
    stammdaten_text:      "Laden Sie die am PC exportierte Datei, um Konten und Kategorien für die Erfassung zu übernehmen.",
    stammdaten_laden:     "Stammdaten laden",
    status_leer:          "Noch keine Stammdaten geladen.",
    status_geladen:       "Geladen: {konten} Konten, {kategorien} Kategorien",
    status_stand:         "Stand: {datum}",
    erfolg_geladen:       "Stammdaten erfolgreich geladen.",
    setup_erfolg:         "Einrichtung erfolgreich! {konten} Konten geladen.",
    install_titel:        "Als App installieren",
    install_sub:          "Für schnellen Zugriff vom Startbildschirm",
    install_btn:          "Installieren",
    install_ios_hinweis:  "Teilen-Symbol antippen, dann „Zum Home-Bildschirm“.",
    fehler_ungueltig:     "Die Datei ist keine gültige BudgetView-Stammdatendatei.",
    fehler_lesen:         "Die Datei konnte nicht gelesen werden."
  },
  en: {
    app_titel:            "BudgetView",
    untertitel:           "Capture receipts on the go",
    nav_erfassen:         "Capture",
    nav_inbox:            "Inbox",
    nav_einstellungen:    "Settings",

    erfassen_titel:       "Capture",
    typ_ausgabe:          "Expense",
    typ_einnahme:         "Income",
    feld_datum:           "Date",
    feld_betrag:          "Amount",
    feld_konto:           "Account",
    feld_hauptkat:        "Main category",
    feld_unterkat:        "Subcategory",
    feld_beschreibung:    "Description",
    ph_bitte_waehlen:     "Please select",
    ph_beschreibung:      "e.g. weekly groceries",
    btn_speichern:        "Save entry",
    feld_belege:          "Receipts",
    foto_hinzufuegen:     "Add photo",
    foto_entfernen:       "Remove photo",
    fehler_foto:          "The photo could not be processed.",
    fehler_speichern:     "The entry could not be saved.",
    erfolg_gespeichert:   "Entry saved.",
    fehler_pflicht:       "Please fill in amount, account and category.",
    fehler_betrag:        "Please enter a valid amount.",

    keine_sd_titel:       "No master data yet",
    keine_sd_text:        "Please first load your accounts and categories from your PC under “Settings”.",
    keine_sd_btn:         "Go to settings",

    inbox_titel:          "Inbox",
    inbox_leer:           "No entries captured yet.",
    inbox_anzahl:         "{anzahl} entry/entries waiting for export",
    inbox_loeschen:       "Delete",
    inbox_bearbeiten:     "Edit",
    inbox_export:         "Export entries",
    export_titel:         "Encrypt export",
    export_text:          "Choose a password. You will need it again when importing on your PC. Without it, the data cannot be read.",
    export_pw1:           "Password",
    export_pw2:           "Repeat password",
    export_btn:           "Export",
    btn_speichern_datei:  "Save",
    btn_teilen:           "Share",
    btn_weiter:           "Continue",
    btn_schliessen:       "Close",
    phase2_titel:         "Export ready",
    phase2_text:          "Your file is encrypted. How would you like to share it?",
    fehler_pw_leer:       "Please enter a password.",
    fehler_pw_ungleich:   "The passwords do not match.",
    fehler_export_leer:   "There are no entries to export.",
    fehler_export:        "The export failed.",
    erfolg_export:        "Entries were exported encrypted.",
    loeschen_titel:       "Transfer successful",
    loeschen_frage:       "Delete the {anzahl} transferred bookings from your phone now?",
    loeschen_datei_hinweis: "The file \u201c{datei}\u201d is now in your Download folder. Once you have imported it on your PC, you can safely delete it there.",
    loeschen_ja:          "Yes, delete",
    loeschen_nein:        "No, keep them",
    loeschen_erfolg:      "Transferred bookings deleted.",
    pw_titel_festlegen:   "Set password",
    pw_titel_eingeben:    "Enter password",
    pw_text_festlegen:    "Set a password for the export. You will need it when importing on your PC. The optional hint helps you if you forget it.",
    pw_text_eingeben:     "Enter your export password.",
    pw_hinweis_ph:        "Password hint (optional)",
    pw_hinweis_label:     "Your hint: {hinweis}",
    fehler_pw_falsch:     "Wrong password.",
    fehler_teilen_nicht:  "Sharing is not supported on this device. Please use \u201cSave\u201d.",
    fehler_teilen_fehler: "Sharing failed (reason: {grund}).",
    erfassen_titel_bearbeiten: "Edit entry",
    btn_aenderungen:      "Save changes",
    btn_abbrechen:        "Cancel",

    einstellungen_titel:  "Settings",
    sprache_titel:        "Language",
    stammdaten_titel:     "Master data from PC",
    stammdaten_text:      "Load the file exported on your PC to import accounts and categories for capturing.",
    stammdaten_laden:     "Load master data",
    status_leer:          "No master data loaded yet.",
    status_geladen:       "Loaded: {konten} accounts, {kategorien} categories",
    status_stand:         "As of: {datum}",
    erfolg_geladen:       "Master data loaded successfully.",
    setup_erfolg:         "Setup complete! {konten} accounts loaded.",
    install_titel:        "Install as app",
    install_sub:          "For quick access from your home screen",
    install_btn:          "Install",
    install_ios_hinweis:  "Tap the Share icon, then “Add to Home Screen”.",
    fehler_ungueltig:     "The file is not a valid BudgetView master data file.",
    fehler_lesen:         "The file could not be read."
  },
  pt_br: {
    app_titel:            "BudgetView",
    untertitel:           "Registre comprovantes em qualquer lugar",
    nav_erfassen:         "Registrar",
    nav_inbox:            "Caixa de entrada",
    nav_einstellungen:    "Configurações",

    erfassen_titel:       "Registrar",
    typ_ausgabe:          "Despesa",
    typ_einnahme:         "Receita",
    feld_datum:           "Data",
    feld_betrag:          "Valor",
    feld_konto:           "Conta",
    feld_hauptkat:        "Categoria principal",
    feld_unterkat:        "Subcategoria",
    feld_beschreibung:    "Descrição",
    ph_bitte_waehlen:     "Selecione",
    ph_beschreibung:      "ex.: compras da semana",
    btn_speichern:        "Salvar lançamento",
    feld_belege:          "Comprovantes",
    foto_hinzufuegen:     "Adicionar foto",
    foto_entfernen:       "Remover foto",
    fehler_foto:          "Não foi possível processar a foto.",
    fehler_speichern:     "Não foi possível salvar o lançamento.",
    erfolg_gespeichert:   "Lançamento salvo.",
    fehler_pflicht:       "Preencha valor, conta e categoria.",
    fehler_betrag:        "Digite um valor válido.",

    keine_sd_titel:       "Ainda sem dados-mestre",
    keine_sd_text:        "Primeiro carregue suas contas e categorias do PC em “Configurações”.",
    keine_sd_btn:         "Ir para configurações",

    inbox_titel:          "Caixa de entrada",
    inbox_leer:           "Nenhum lançamento registrado ainda.",
    inbox_anzahl:         "{anzahl} lançamento(s) aguardando exportação",
    inbox_loeschen:       "Excluir",
    inbox_bearbeiten:     "Editar",
    inbox_export:         "Exportar lançamentos",
    export_titel:         "Criptografar exportação",
    export_text:          "Defina uma senha. Você precisará dela ao importar no PC. Sem a senha, os dados não podem ser lidos.",
    export_pw1:           "Senha",
    export_pw2:           "Repetir senha",
    export_btn:           "Exportar",
    btn_speichern_datei:  "Salvar",
    btn_teilen:           "Compartilhar",
    btn_weiter:           "Continuar",
    btn_schliessen:       "Fechar",
    phase2_titel:         "Exportação pronta",
    phase2_text:          "Seu arquivo está criptografado. Como deseja compartilhá-lo?",
    fehler_pw_leer:       "Digite uma senha.",
    fehler_pw_ungleich:   "As senhas não coincidem.",
    fehler_export_leer:   "Não há lançamentos para exportar.",
    fehler_export:        "A exportação falhou.",
    erfolg_export:        "Lançamentos exportados com criptografia.",
    loeschen_titel:       "Transferência concluída",
    loeschen_frage:       "Excluir agora os {anzahl} lançamentos transferidos do celular?",
    loeschen_datei_hinweis: "O arquivo \u201c{datei}\u201d está agora na pasta Download. Depois de importar no PC, você pode excluí-lo com segurança.",
    loeschen_ja:          "Sim, excluir",
    loeschen_nein:        "Não, manter",
    loeschen_erfolg:      "Lançamentos transferidos excluídos.",
    pw_titel_festlegen:   "Definir senha",
    pw_titel_eingeben:    "Digite a senha",
    pw_text_festlegen:    "Defina uma senha para a exportação. Você precisará dela ao importar no PC. A dica opcional ajuda caso você esqueça.",
    pw_text_eingeben:     "Digite sua senha de exportação.",
    pw_hinweis_ph:        "Dica da senha (opcional)",
    pw_hinweis_label:     "Sua dica: {hinweis}",
    fehler_pw_falsch:     "Senha incorreta.",
    fehler_teilen_nicht:  "O compartilhamento não é compatível neste dispositivo. Use \u201cSalvar\u201d.",
    fehler_teilen_fehler: "Falha ao compartilhar (motivo: {grund}).",
    erfassen_titel_bearbeiten: "Editar lançamento",
    btn_aenderungen:      "Salvar alterações",
    btn_abbrechen:        "Cancelar",

    einstellungen_titel:  "Configurações",
    sprache_titel:        "Idioma",
    stammdaten_titel:     "Dados-mestre do PC",
    stammdaten_text:      "Carregue o arquivo exportado no PC para importar contas e categorias para o registro.",
    stammdaten_laden:     "Carregar dados-mestre",
    status_leer:          "Nenhum dado-mestre carregado ainda.",
    status_geladen:       "Carregado: {konten} contas, {kategorien} categorias",
    status_stand:         "Em: {datum}",
    erfolg_geladen:       "Dados-mestre carregados com sucesso.",
    setup_erfolg:         "Configuração concluída! {konten} contas carregadas.",
    install_titel:        "Instalar como app",
    install_sub:          "Para acesso rápido pela tela inicial",
    install_btn:          "Instalar",
    install_ios_hinweis:  "Toque no ícone Compartilhar e em “Adicionar à Tela de Início”.",
    fehler_ungueltig:     "O arquivo não é um arquivo de dados-mestre válido do BudgetView.",
    fehler_lesen:         "Não foi possível ler o arquivo."
  }
};

let AKTUELLE_SPRACHE = "de";

// Locale fuer die Datumsanzeige je Sprache.
const LOCALE = { de: "de-DE", en: "en-US", pt_br: "pt-BR" };

function t(schluessel, ersetzungen) {
  const paket = LANG[AKTUELLE_SPRACHE] || LANG.de;
  let text = paket[schluessel] || schluessel;
  if (ersetzungen) {
    for (const key in ersetzungen) {
      text = text.split("{" + key + "}").join(String(ersetzungen[key]));
    }
  }
  return text;
}
